apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-deploy
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: auth
    spec:
      containers:
      - env:
        - name: DB_ADDR
          value: postgres
        - name: DB_DATABASE
          value: postgres
        - name: DB_PASSWORD
          value: dalong
        - name: DB_USER
          value: postgres
        - name: DB_VENDOR
          value: postgres
        - name: KEYCLOAK_PASSWORD
          value: dalongrong
        - name: KEYCLOAK_USER
          value: dalong
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        image: jboss/keycloak
        name: auth
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
