apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-deploy
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: openresty
  name: openresty
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 80
  selector:
    io.kompose.service: openresty
status:
  loadBalancer: {}
